# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
  - job: GitGuardianShield
    pool:
      vmImage: 'ubuntu-latest'
    container: xblanchotgg/ggshield:latest
    steps:
      - checkout: self
        fetchDepth: 2 # Required to allow scanning last commit in push events
      - script: |
          ggshield sca scan ci -v
        env:
          GITGUARDIAN_API_KEY: $(gitguardianApiKey)